[project]
name = "amigainfo"
description = "Load, save and export Amiga .info files"
version = "0.4.2"
authors = [
    { name = "Gareth Davidson", email = "gaz@bitplane.net" }
]
readme = "README.md"
license = "WTFPL"
requires-python = ">=3.10"

dependencies = [
    "pillow>=12.1"
]

[project.urls]
Homepage = "https://bitplane.net/dev/python/amigainfo"
Repository = "https://github.com/bitplane/amigainfo"
Issues = "https://github.com/bitplane/amigainfo/issues"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
    "coverage",
    "pytest-cov",
    "build",
    "twine",
    "ruff",
    "mkdocs",
    "mkdocs-material",
    "pydoc-markdown"
]

[project.scripts]
amigainfo = "amigainfo.__main__:main"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.format]
docstring-code-format = true
